// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/article.proto

/*
Package article is a generated protocol buffer package.

It is generated from these files:
	protos/article.proto

It has these top-level messages:
	QueryRequest
	ArticleInfo
	ArticleList
*/
package article

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type QueryRequest struct {
	Id    int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Limit int64 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Page  int64 `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueryRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *QueryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ArticleInfo struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Slug      string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	Summary   string `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	Body      string `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	Image     string `protobuf:"bytes,6,opt,name=image" json:"image,omitempty"`
	Views     int64  `protobuf:"varint,7,opt,name=views" json:"views,omitempty"`
	UserId    int32  `protobuf:"varint,8,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	CreatedAt string `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *ArticleInfo) Reset()                    { *m = ArticleInfo{} }
func (m *ArticleInfo) String() string            { return proto.CompactTextString(m) }
func (*ArticleInfo) ProtoMessage()               {}
func (*ArticleInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ArticleInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleInfo) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *ArticleInfo) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ArticleInfo) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ArticleInfo) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ArticleInfo) GetViews() int64 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *ArticleInfo) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ArticleInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ArticleInfo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ArticleList struct {
	List []*ArticleInfo `protobuf:"bytes,1,rep,name=list" json:"list,omitempty"`
}

func (m *ArticleList) Reset()                    { *m = ArticleList{} }
func (m *ArticleList) String() string            { return proto.CompactTextString(m) }
func (*ArticleList) ProtoMessage()               {}
func (*ArticleList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ArticleList) GetList() []*ArticleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryRequest)(nil), "article.queryRequest")
	proto.RegisterType((*ArticleInfo)(nil), "article.articleInfo")
	proto.RegisterType((*ArticleList)(nil), "article.articleList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Article service

type ArticleClient interface {
	GetArticleInfo(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ArticleInfo, error)
	GetArticleList(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ArticleList, error)
}

type articleClient struct {
	cc *grpc.ClientConn
}

func NewArticleClient(cc *grpc.ClientConn) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) GetArticleInfo(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ArticleInfo, error) {
	out := new(ArticleInfo)
	err := grpc.Invoke(ctx, "/article.Article/GetArticleInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) GetArticleList(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*ArticleList, error) {
	out := new(ArticleList)
	err := grpc.Invoke(ctx, "/article.Article/GetArticleList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Article service

type ArticleServer interface {
	GetArticleInfo(context.Context, *QueryRequest) (*ArticleInfo, error)
	GetArticleList(context.Context, *QueryRequest) (*ArticleList, error)
}

func RegisterArticleServer(s *grpc.Server, srv ArticleServer) {
	s.RegisterService(&_Article_serviceDesc, srv)
}

func _Article_GetArticleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/GetArticleInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticleInfo(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_GetArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/GetArticleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticleList(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Article_serviceDesc = grpc.ServiceDesc{
	ServiceName: "article.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticleInfo",
			Handler:    _Article_GetArticleInfo_Handler,
		},
		{
			MethodName: "GetArticleList",
			Handler:    _Article_GetArticleList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/article.proto",
}

func init() { proto.RegisterFile("protos/article.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0x87, 0xbb, 0xfd, 0x17, 0x33, 0x95, 0x1e, 0x96, 0x8a, 0x8b, 0x20, 0x94, 0x9c, 0x72, 0xaa,
	0x50, 0x0f, 0x1e, 0x25, 0x27, 0x2d, 0x78, 0xda, 0x17, 0x28, 0x69, 0x77, 0x2d, 0x0b, 0x89, 0x69,
	0x77, 0x67, 0x95, 0x3e, 0x83, 0x2f, 0xec, 0x51, 0x76, 0x36, 0x2d, 0x11, 0x7a, 0xf0, 0x36, 0xdf,
	0x6f, 0x26, 0x1f, 0x93, 0x49, 0x60, 0xb6, 0xb7, 0x0d, 0x36, 0xee, 0xa1, 0xb4, 0x68, 0xb6, 0x95,
	0x5e, 0x10, 0xf2, 0xa4, 0xc5, 0xec, 0x15, 0xae, 0x0f, 0x5e, 0xdb, 0xa3, 0xd4, 0x07, 0xaf, 0x1d,
	0xf2, 0x29, 0xf4, 0x8d, 0x12, 0x6c, 0xce, 0xf2, 0x81, 0xec, 0x1b, 0xc5, 0x67, 0x30, 0xaa, 0x4c,
	0x6d, 0x50, 0xf4, 0x29, 0x8a, 0xc0, 0x39, 0x0c, 0xf7, 0xe5, 0x4e, 0x8b, 0x01, 0x85, 0x54, 0x67,
	0x3f, 0x0c, 0x26, 0xad, 0x75, 0xf5, 0xf1, 0xde, 0x5c, 0x32, 0xa1, 0xc1, 0x4a, 0x93, 0x29, 0x95,
	0x11, 0x82, 0xc9, 0x55, 0x7e, 0x47, 0xa6, 0x54, 0x52, 0xcd, 0x05, 0x24, 0xce, 0xd7, 0x75, 0x69,
	0x8f, 0x62, 0x48, 0xf1, 0x09, 0xc3, 0xf4, 0xa6, 0x51, 0x47, 0x31, 0x8a, 0xd3, 0xa1, 0x0e, 0x5e,
	0x53, 0x87, 0x65, 0xc6, 0xd1, 0x4b, 0x10, 0xd2, 0x4f, 0xa3, 0xbf, 0x9c, 0x48, 0xe2, 0xde, 0x04,
	0xfc, 0x16, 0x12, 0xef, 0xb4, 0x5d, 0x1b, 0x25, 0xae, 0xe6, 0x2c, 0x1f, 0xc9, 0x71, 0xc0, 0x95,
	0xe2, 0xf7, 0x00, 0x5b, 0xab, 0x4b, 0xd4, 0x6a, 0x5d, 0xa2, 0x48, 0xc9, 0x94, 0xb6, 0x49, 0x81,
	0xa1, 0xed, 0xf7, 0xea, 0xd4, 0x86, 0xd8, 0x6e, 0x93, 0x02, 0xb3, 0xa7, 0xf3, 0x9b, 0xbf, 0x19,
	0x87, 0x3c, 0x87, 0x61, 0x65, 0x1c, 0x0a, 0x36, 0x1f, 0xe4, 0x93, 0xe5, 0x6c, 0x71, 0x3a, 0x7d,
	0xe7, 0x3a, 0x92, 0x26, 0x96, 0xdf, 0x0c, 0x92, 0x22, 0xa6, 0xfc, 0x19, 0xa6, 0x2f, 0x1a, 0x8b,
	0xce, 0x05, 0x6f, 0xce, 0x4f, 0x76, 0x3f, 0xd1, 0xdd, 0x45, 0x61, 0xd6, 0xfb, 0x2b, 0xa0, 0x45,
	0xfe, 0x2b, 0x08, 0xc3, 0x59, 0x6f, 0x33, 0xa6, 0x7f, 0xe3, 0xf1, 0x37, 0x00, 0x00, 0xff, 0xff,
	0xb6, 0xe6, 0x7c, 0x22, 0x33, 0x02, 0x00, 0x00,
}
