// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/article.proto

/*
Package article is a generated protocol buffer package.

It is generated from these files:
	protos/article.proto

It has these top-level messages:
	Request
	ArticleInfoResponse
*/
package article

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Request) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ArticleInfoResponse struct {
	Id        int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Slug      string `protobuf:"bytes,3,opt,name=slug" json:"slug,omitempty"`
	Summary   string `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	Body      string `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	Image     string `protobuf:"bytes,6,opt,name=image" json:"image,omitempty"`
	Views     int64  `protobuf:"varint,7,opt,name=views" json:"views,omitempty"`
	UserId    int32  `protobuf:"varint,8,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	CreatedAt string `protobuf:"bytes,9,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *ArticleInfoResponse) Reset()                    { *m = ArticleInfoResponse{} }
func (m *ArticleInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*ArticleInfoResponse) ProtoMessage()               {}
func (*ArticleInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ArticleInfoResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleInfoResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleInfoResponse) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *ArticleInfoResponse) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ArticleInfoResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ArticleInfoResponse) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ArticleInfoResponse) GetViews() int64 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *ArticleInfoResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ArticleInfoResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ArticleInfoResponse) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "article.Request")
	proto.RegisterType((*ArticleInfoResponse)(nil), "article.ArticleInfoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Article service

type ArticleClient interface {
	GetArticleInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ArticleInfoResponse, error)
}

type articleClient struct {
	cc *grpc.ClientConn
}

func NewArticleClient(cc *grpc.ClientConn) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) GetArticleInfo(ctx context.Context, in *Request, opts ...grpc.CallOption) (*ArticleInfoResponse, error) {
	out := new(ArticleInfoResponse)
	err := grpc.Invoke(ctx, "/article.Article/GetArticleInfo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Article service

type ArticleServer interface {
	GetArticleInfo(context.Context, *Request) (*ArticleInfoResponse, error)
}

func RegisterArticleServer(s *grpc.Server, srv ArticleServer) {
	s.RegisterService(&_Article_serviceDesc, srv)
}

func _Article_GetArticleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/article.Article/GetArticleInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticleInfo(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Article_serviceDesc = grpc.ServiceDesc{
	ServiceName: "article.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticleInfo",
			Handler:    _Article_GetArticleInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/article.proto",
}

func init() { proto.RegisterFile("protos/article.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0xbf, 0xa4, 0x4d, 0xe6, 0xcb, 0x5d, 0x14, 0x19, 0x0b, 0x5e, 0x45, 0x21, 0x64, 0x95,
	0x55, 0x05, 0x7d, 0x82, 0xb8, 0x91, 0x2e, 0xdc, 0xe4, 0x05, 0x4a, 0xda, 0xb9, 0x96, 0x81, 0xa4,
	0x89, 0x99, 0x1b, 0xa5, 0x3b, 0x1f, 0x5d, 0xe6, 0x4f, 0x44, 0xc4, 0xdd, 0xfc, 0xce, 0x3d, 0x1c,
	0x86, 0x1f, 0xac, 0x87, 0xb1, 0xe7, 0xde, 0xdc, 0x37, 0x23, 0xeb, 0x43, 0x4b, 0x1b, 0x87, 0x52,
	0x04, 0x2c, 0xae, 0x41, 0xd4, 0xf4, 0x36, 0x91, 0x61, 0xb9, 0x82, 0x58, 0x2b, 0x8c, 0xf2, 0xa8,
	0x5c, 0xd4, 0xb1, 0x56, 0xc5, 0x67, 0x0c, 0x97, 0x95, 0xaf, 0x6d, 0x4f, 0xaf, 0x7d, 0x4d, 0x66,
	0xe8, 0x4f, 0x86, 0x7e, 0xf7, 0xe4, 0x1a, 0x12, 0xd6, 0xdc, 0x12, 0xc6, 0x79, 0x54, 0x66, 0xb5,
	0x07, 0x29, 0x61, 0x69, 0xda, 0xe9, 0x88, 0x0b, 0x17, 0xba, 0xb7, 0x44, 0x10, 0x66, 0xea, 0xba,
	0x66, 0x3c, 0xe3, 0xd2, 0xc5, 0x33, 0xda, 0xf6, 0xbe, 0x57, 0x67, 0x4c, 0x7c, 0xdb, 0xbe, 0xed,
	0xae, 0xee, 0x9a, 0x23, 0x61, 0xea, 0x77, 0x1d, 0xd8, 0xf4, 0x5d, 0xd3, 0x87, 0x41, 0xe1, 0x3e,
	0xe0, 0x41, 0x5e, 0x81, 0x98, 0x0c, 0x8d, 0x3b, 0xad, 0xf0, 0x7f, 0x1e, 0x95, 0x49, 0x9d, 0x5a,
	0xdc, 0x2a, 0x79, 0x07, 0x70, 0x18, 0xa9, 0x61, 0x52, 0xbb, 0x86, 0x31, 0x73, 0x4b, 0x59, 0x48,
	0x2a, 0xb6, 0xe7, 0x69, 0x50, 0xf3, 0x19, 0xfc, 0x39, 0x24, 0x15, 0x3f, 0xbc, 0x80, 0x08, 0x06,
	0xe4, 0x13, 0xac, 0x9e, 0x89, 0x7f, 0xf8, 0x90, 0x17, 0x9b, 0xd9, 0x69, 0x30, 0x78, 0x73, 0xfb,
	0x9d, 0xfc, 0xe1, 0xad, 0xf8, 0xb7, 0x4f, 0x9d, 0xfc, 0xc7, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x5b, 0x4d, 0xe0, 0x27, 0x94, 0x01, 0x00, 0x00,
}
