// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AQueryRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AQueryRequest) Reset()         { *m = AQueryRequest{} }
func (m *AQueryRequest) String() string { return proto.CompactTextString(m) }
func (*AQueryRequest) ProtoMessage()    {}
func (*AQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_fd660c2fb633dd36, []int{0}
}
func (m *AQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AQueryRequest.Unmarshal(m, b)
}
func (m *AQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AQueryRequest.Marshal(b, m, deterministic)
}
func (dst *AQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AQueryRequest.Merge(dst, src)
}
func (m *AQueryRequest) XXX_Size() int {
	return xxx_messageInfo_AQueryRequest.Size(m)
}
func (m *AQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AQueryRequest proto.InternalMessageInfo

func (m *AQueryRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AQueryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *AQueryRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type ArticleInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Summary              string   `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	Body                 string   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Image                string   `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Views                int64    `protobuf:"varint,7,opt,name=views,proto3" json:"views,omitempty"`
	UserId               int64    `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            string   `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArticleInfo) Reset()         { *m = ArticleInfo{} }
func (m *ArticleInfo) String() string { return proto.CompactTextString(m) }
func (*ArticleInfo) ProtoMessage()    {}
func (*ArticleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_fd660c2fb633dd36, []int{1}
}
func (m *ArticleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleInfo.Unmarshal(m, b)
}
func (m *ArticleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleInfo.Marshal(b, m, deterministic)
}
func (dst *ArticleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleInfo.Merge(dst, src)
}
func (m *ArticleInfo) XXX_Size() int {
	return xxx_messageInfo_ArticleInfo.Size(m)
}
func (m *ArticleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleInfo proto.InternalMessageInfo

func (m *ArticleInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArticleInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleInfo) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *ArticleInfo) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *ArticleInfo) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ArticleInfo) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *ArticleInfo) GetViews() int64 {
	if m != nil {
		return m.Views
	}
	return 0
}

func (m *ArticleInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ArticleInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *ArticleInfo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type ArticleList struct {
	List                 []*ArticleInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ArticleList) Reset()         { *m = ArticleList{} }
func (m *ArticleList) String() string { return proto.CompactTextString(m) }
func (*ArticleList) ProtoMessage()    {}
func (*ArticleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_article_fd660c2fb633dd36, []int{2}
}
func (m *ArticleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArticleList.Unmarshal(m, b)
}
func (m *ArticleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArticleList.Marshal(b, m, deterministic)
}
func (dst *ArticleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArticleList.Merge(dst, src)
}
func (m *ArticleList) XXX_Size() int {
	return xxx_messageInfo_ArticleList.Size(m)
}
func (m *ArticleList) XXX_DiscardUnknown() {
	xxx_messageInfo_ArticleList.DiscardUnknown(m)
}

var xxx_messageInfo_ArticleList proto.InternalMessageInfo

func (m *ArticleList) GetList() []*ArticleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*AQueryRequest)(nil), "protos.AQueryRequest")
	proto.RegisterType((*ArticleInfo)(nil), "protos.ArticleInfo")
	proto.RegisterType((*ArticleList)(nil), "protos.ArticleList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ArticleClient is the client API for Article service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ArticleClient interface {
	GetArticleInfo(ctx context.Context, in *AQueryRequest, opts ...grpc.CallOption) (*ArticleInfo, error)
	GetArticleList(ctx context.Context, in *AQueryRequest, opts ...grpc.CallOption) (*ArticleList, error)
}

type articleClient struct {
	cc *grpc.ClientConn
}

func NewArticleClient(cc *grpc.ClientConn) ArticleClient {
	return &articleClient{cc}
}

func (c *articleClient) GetArticleInfo(ctx context.Context, in *AQueryRequest, opts ...grpc.CallOption) (*ArticleInfo, error) {
	out := new(ArticleInfo)
	err := c.cc.Invoke(ctx, "/protos.Article/GetArticleInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleClient) GetArticleList(ctx context.Context, in *AQueryRequest, opts ...grpc.CallOption) (*ArticleList, error) {
	out := new(ArticleList)
	err := c.cc.Invoke(ctx, "/protos.Article/GetArticleList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServer is the server API for Article service.
type ArticleServer interface {
	GetArticleInfo(context.Context, *AQueryRequest) (*ArticleInfo, error)
	GetArticleList(context.Context, *AQueryRequest) (*ArticleList, error)
}

func RegisterArticleServer(s *grpc.Server, srv ArticleServer) {
	s.RegisterService(&_Article_serviceDesc, srv)
}

func _Article_GetArticleInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticleInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Article/GetArticleInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticleInfo(ctx, req.(*AQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Article_GetArticleList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServer).GetArticleList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Article/GetArticleList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServer).GetArticleList(ctx, req.(*AQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Article_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Article",
	HandlerType: (*ArticleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetArticleInfo",
			Handler:    _Article_GetArticleInfo_Handler,
		},
		{
			MethodName: "GetArticleList",
			Handler:    _Article_GetArticleList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "article.proto",
}

func init() { proto.RegisterFile("article.proto", fileDescriptor_article_fd660c2fb633dd36) }

var fileDescriptor_article_fd660c2fb633dd36 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0x6a, 0xeb, 0x30,
	0x14, 0xc6, 0xb1, 0xf3, 0xc7, 0xd7, 0x0a, 0x09, 0x17, 0xdd, 0x1b, 0xae, 0xc8, 0x6d, 0x21, 0x78,
	0x69, 0xc8, 0x10, 0xd3, 0x14, 0x3a, 0x64, 0xf3, 0x54, 0x02, 0x5d, 0xea, 0xad, 0x53, 0x50, 0x62,
	0xc5, 0x08, 0x6c, 0xcb, 0xb5, 0x8e, 0x53, 0xb2, 0xf6, 0x15, 0xfa, 0x40, 0x7d, 0x88, 0xbe, 0x42,
	0x1f, 0xa2, 0x63, 0xd1, 0x91, 0x13, 0x52, 0xc8, 0xd0, 0xc9, 0xfa, 0xbe, 0xf3, 0xf9, 0xc7, 0xe7,
	0x63, 0x91, 0x3e, 0xaf, 0x40, 0x6e, 0x32, 0x31, 0x2b, 0x2b, 0x05, 0x8a, 0x76, 0xf1, 0xa1, 0x47,
	0x17, 0xa9, 0x52, 0x69, 0x26, 0x42, 0x5e, 0xca, 0x90, 0x17, 0x85, 0x02, 0x0e, 0x52, 0x15, 0xda,
	0xa6, 0x82, 0x25, 0xe9, 0x47, 0x0f, 0xb5, 0xa8, 0xf6, 0xb1, 0x78, 0xaa, 0x85, 0x06, 0x3a, 0x20,
	0xae, 0x4c, 0x98, 0x33, 0x76, 0x26, 0xad, 0xd8, 0x95, 0x09, 0xfd, 0x4b, 0x3a, 0x99, 0xcc, 0x25,
	0x30, 0x17, 0x2d, 0x2b, 0x28, 0x25, 0xed, 0x92, 0xa7, 0x82, 0xb5, 0xd0, 0xc4, 0x73, 0xf0, 0xe9,
	0x90, 0x5e, 0x64, 0x2b, 0x2c, 0x8b, 0xad, 0x3a, 0x47, 0x02, 0x09, 0x99, 0x40, 0x92, 0x1f, 0x5b,
	0x61, 0x48, 0x3a, 0xab, 0x53, 0x24, 0xf9, 0x31, 0x9e, 0x29, 0x23, 0x9e, 0xae, 0xf3, 0x9c, 0x57,
	0x7b, 0xd6, 0x46, 0xfb, 0x20, 0x4d, 0x7a, 0xad, 0x92, 0x3d, 0xeb, 0xd8, 0xb4, 0x39, 0x1b, 0xae,
	0xcc, 0x4d, 0x99, 0xae, 0xe5, 0xa2, 0x30, 0xee, 0x4e, 0x8a, 0x67, 0xcd, 0x3c, 0xdb, 0x1b, 0x05,
	0xfd, 0x47, 0xbc, 0x5a, 0x8b, 0x6a, 0x25, 0x13, 0xf6, 0x0b, 0xfd, 0xae, 0x91, 0xcb, 0x84, 0x5e,
	0x12, 0xb2, 0xa9, 0x04, 0x07, 0x91, 0xac, 0x38, 0x30, 0x1f, 0x49, 0x7e, 0xe3, 0x44, 0x60, 0xc6,
	0x75, 0x99, 0x1c, 0xc6, 0xc4, 0x8e, 0x1b, 0x27, 0x82, 0xe0, 0xf6, 0xf8, 0xe5, 0xf7, 0x52, 0x03,
	0xbd, 0x22, 0xed, 0x4c, 0x6a, 0x60, 0xce, 0xb8, 0x35, 0xe9, 0xcd, 0xff, 0xd8, 0x55, 0xeb, 0xd9,
	0xc9, 0x72, 0x62, 0x0c, 0xcc, 0xdf, 0x1c, 0xe2, 0x35, 0x2e, 0x7d, 0x24, 0x83, 0x3b, 0x01, 0xa7,
	0x0b, 0x1c, 0x1e, 0x5f, 0x3c, 0xfd, 0x43, 0xa3, 0x73, 0xbc, 0xe0, 0xff, 0xcb, 0xfb, 0xc7, 0xab,
	0x3b, 0x0c, 0x7e, 0x87, 0xbb, 0xeb, 0xb0, 0xb9, 0x08, 0xa1, 0x2c, 0xb6, 0x6a, 0xe1, 0x4c, 0xbf,
	0xa3, 0xb1, 0xe1, 0x0f, 0xd1, 0x26, 0x7b, 0x1e, 0x6d, 0xea, 0x2f, 0x9c, 0xe9, 0xda, 0xde, 0xb2,
	0x9b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x92, 0x83, 0x11, 0xa2, 0x7d, 0x02, 0x00, 0x00,
}
