// Code generated by protoc-gen-go. DO NOT EDIT.
// source: category.proto

package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CQueryRequest struct {
	CatId                int64    `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page                 int64    `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CQueryRequest) Reset()         { *m = CQueryRequest{} }
func (m *CQueryRequest) String() string { return proto.CompactTextString(m) }
func (*CQueryRequest) ProtoMessage()    {}
func (*CQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_ca907a550b518c5a, []int{0}
}
func (m *CQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CQueryRequest.Unmarshal(m, b)
}
func (m *CQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CQueryRequest.Marshal(b, m, deterministic)
}
func (dst *CQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CQueryRequest.Merge(dst, src)
}
func (m *CQueryRequest) XXX_Size() int {
	return xxx_messageInfo_CQueryRequest.Size(m)
}
func (m *CQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CQueryRequest proto.InternalMessageInfo

func (m *CQueryRequest) GetCatId() int64 {
	if m != nil {
		return m.CatId
	}
	return 0
}

func (m *CQueryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *CQueryRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

type CategoryInfo struct {
	CatId                int64    `protobuf:"varint,1,opt,name=cat_id,json=catId,proto3" json:"cat_id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ParentId             int64    `protobuf:"varint,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Sort                 int64    `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CategoryInfo) Reset()         { *m = CategoryInfo{} }
func (m *CategoryInfo) String() string { return proto.CompactTextString(m) }
func (*CategoryInfo) ProtoMessage()    {}
func (*CategoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_ca907a550b518c5a, []int{1}
}
func (m *CategoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryInfo.Unmarshal(m, b)
}
func (m *CategoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryInfo.Marshal(b, m, deterministic)
}
func (dst *CategoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryInfo.Merge(dst, src)
}
func (m *CategoryInfo) XXX_Size() int {
	return xxx_messageInfo_CategoryInfo.Size(m)
}
func (m *CategoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryInfo proto.InternalMessageInfo

func (m *CategoryInfo) GetCatId() int64 {
	if m != nil {
		return m.CatId
	}
	return 0
}

func (m *CategoryInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CategoryInfo) GetParentId() int64 {
	if m != nil {
		return m.ParentId
	}
	return 0
}

func (m *CategoryInfo) GetSort() int64 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *CategoryInfo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *CategoryInfo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type CategoryList struct {
	Data                 []*CategoryInfo `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CategoryList) Reset()         { *m = CategoryList{} }
func (m *CategoryList) String() string { return proto.CompactTextString(m) }
func (*CategoryList) ProtoMessage()    {}
func (*CategoryList) Descriptor() ([]byte, []int) {
	return fileDescriptor_category_ca907a550b518c5a, []int{2}
}
func (m *CategoryList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CategoryList.Unmarshal(m, b)
}
func (m *CategoryList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CategoryList.Marshal(b, m, deterministic)
}
func (dst *CategoryList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CategoryList.Merge(dst, src)
}
func (m *CategoryList) XXX_Size() int {
	return xxx_messageInfo_CategoryList.Size(m)
}
func (m *CategoryList) XXX_DiscardUnknown() {
	xxx_messageInfo_CategoryList.DiscardUnknown(m)
}

var xxx_messageInfo_CategoryList proto.InternalMessageInfo

func (m *CategoryList) GetData() []*CategoryInfo {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CQueryRequest)(nil), "protos.CQueryRequest")
	proto.RegisterType((*CategoryInfo)(nil), "protos.CategoryInfo")
	proto.RegisterType((*CategoryList)(nil), "protos.CategoryList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CategoryClient is the client API for Category service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CategoryClient interface {
	GetCategoryInfo(ctx context.Context, in *CQueryRequest, opts ...grpc.CallOption) (*CategoryInfo, error)
	GetCategoryList(ctx context.Context, in *CQueryRequest, opts ...grpc.CallOption) (*CategoryList, error)
}

type categoryClient struct {
	cc *grpc.ClientConn
}

func NewCategoryClient(cc *grpc.ClientConn) CategoryClient {
	return &categoryClient{cc}
}

func (c *categoryClient) GetCategoryInfo(ctx context.Context, in *CQueryRequest, opts ...grpc.CallOption) (*CategoryInfo, error) {
	out := new(CategoryInfo)
	err := c.cc.Invoke(ctx, "/protos.Category/GetCategoryInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *categoryClient) GetCategoryList(ctx context.Context, in *CQueryRequest, opts ...grpc.CallOption) (*CategoryList, error) {
	out := new(CategoryList)
	err := c.cc.Invoke(ctx, "/protos.Category/GetCategoryList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CategoryServer is the server API for Category service.
type CategoryServer interface {
	GetCategoryInfo(context.Context, *CQueryRequest) (*CategoryInfo, error)
	GetCategoryList(context.Context, *CQueryRequest) (*CategoryList, error)
}

func RegisterCategoryServer(s *grpc.Server, srv CategoryServer) {
	s.RegisterService(&_Category_serviceDesc, srv)
}

func _Category_GetCategoryInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).GetCategoryInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Category/GetCategoryInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).GetCategoryInfo(ctx, req.(*CQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Category_GetCategoryList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CategoryServer).GetCategoryList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Category/GetCategoryList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CategoryServer).GetCategoryList(ctx, req.(*CQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Category_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Category",
	HandlerType: (*CategoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategoryInfo",
			Handler:    _Category_GetCategoryInfo_Handler,
		},
		{
			MethodName: "GetCategoryList",
			Handler:    _Category_GetCategoryList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "category.proto",
}

func init() { proto.RegisterFile("category.proto", fileDescriptor_category_ca907a550b518c5a) }

var fileDescriptor_category_ca907a550b518c5a = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0xfd, 0xa3, 0x1d, 0xff, 0x70, 0xac, 0x10, 0x6b, 0x85, 0x92, 0x53, 0x4f, 0x0d, 0xd6,
	0x8b, 0xd7, 0xd2, 0x83, 0x14, 0x3c, 0x68, 0x6e, 0x9e, 0xca, 0x34, 0xd9, 0x86, 0x85, 0x98, 0x8d,
	0xbb, 0x53, 0xa1, 0x88, 0x17, 0x5f, 0xc1, 0xb7, 0xf0, 0x4d, 0x3c, 0xfb, 0x0a, 0x3e, 0x88, 0x74,
	0xb7, 0xd5, 0x06, 0x44, 0x3c, 0xed, 0xcc, 0x37, 0xdf, 0x7e, 0xdf, 0xcc, 0xec, 0xc2, 0x7e, 0x4c,
	0x2c, 0x52, 0xa5, 0x97, 0x83, 0x42, 0x2b, 0x56, 0xd8, 0xb0, 0x87, 0xe9, 0x74, 0x53, 0xa5, 0xd2,
	0x4c, 0x84, 0x54, 0xc8, 0x90, 0xf2, 0x5c, 0x31, 0xb1, 0x54, 0xb9, 0x71, 0xac, 0xe0, 0x06, 0xf6,
	0xc6, 0xb7, 0x0b, 0xa1, 0x97, 0x91, 0x78, 0x58, 0x08, 0xc3, 0x78, 0x0c, 0x8d, 0x98, 0x78, 0x2a,
	0x13, 0xdf, 0xeb, 0x79, 0xfd, 0x6a, 0x54, 0x8f, 0x89, 0x27, 0x09, 0xb6, 0xa1, 0x9e, 0xc9, 0x7b,
	0xc9, 0x7e, 0xc5, 0xa1, 0x36, 0x41, 0x84, 0x5a, 0x41, 0xa9, 0xf0, 0xab, 0x16, 0xb4, 0x71, 0xf0,
	0xe6, 0xc1, 0xee, 0x78, 0xdd, 0xca, 0x24, 0x9f, 0xab, 0x3f, 0x14, 0x59, 0x72, 0x26, 0xac, 0x62,
	0x2b, 0x72, 0x09, 0x9e, 0x42, 0xab, 0x20, 0x2d, 0x72, 0xcb, 0x77, 0xb2, 0x4d, 0x07, 0x4c, 0x92,
	0x95, 0x9d, 0x51, 0x9a, 0xfd, 0x9a, 0xb3, 0x5b, 0xc5, 0x78, 0x06, 0x10, 0x6b, 0x41, 0x2c, 0x92,
	0x29, 0xb1, 0x5f, 0xb7, 0x5a, 0xad, 0x35, 0x32, 0xb2, 0xe5, 0x45, 0x91, 0x6c, 0xca, 0x0d, 0x57,
	0x5e, 0x23, 0x23, 0x0e, 0x2e, 0x7f, 0x7a, 0xbd, 0x96, 0x86, 0xb1, 0x0f, 0xb5, 0x84, 0x98, 0x7c,
	0xaf, 0x57, 0xed, 0xef, 0x0c, 0xdb, 0x6e, 0x49, 0x66, 0xb0, 0x3d, 0x4f, 0x64, 0x19, 0xc3, 0x77,
	0x0f, 0x9a, 0x1b, 0x18, 0x67, 0x70, 0x70, 0x25, 0xb8, 0x3c, 0xf5, 0xf7, 0xdd, 0xed, 0xf5, 0x76,
	0x7e, 0x95, 0x0c, 0x82, 0x97, 0x8f, 0xcf, 0xd7, 0x4a, 0x17, 0x3b, 0xe1, 0xe3, 0x79, 0xb8, 0x79,
	0xc7, 0x50, 0xe6, 0x73, 0x15, 0x3e, 0xb9, 0xdd, 0x3d, 0xe3, 0x5d, 0xc9, 0xc3, 0x76, 0xfb, 0x5f,
	0x8f, 0x15, 0x39, 0x38, 0xb1, 0x1e, 0x47, 0x78, 0x58, 0xf2, 0xc8, 0xa4, 0xe1, 0x99, 0xfb, 0x2a,
	0x17, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x27, 0x06, 0xf4, 0x43, 0x02, 0x00, 0x00,
}
